package com.minibrowser.media;

public final class SurfingKeys {

    private SurfingKeys() { }

    public static String script() {
        return "(function(){"
            + "if(window.__mbSk)return;window.__mbSk=true;"
            + "var MODE='normal';"
            + "var buf='';"
            + "var hintNodes=[],hintLabels=[],hintHolder=null,hintSel='';"
            + "var CHARS='asdfgqwertzxcvb';"
            + "function typing(){var a=document.activeElement;return a&&(a.tagName==='INPUT'||a.tagName==='TEXTAREA'||a.tagName==='SELECT'||a.isContentEditable);}"
            + "function clr(){buf='';}"
            + "function labels(n){var L=Math.max(1,Math.ceil(Math.log(n)/Math.log(CHARS.length)));var out=[];for(var i=0;i<n;i++){var x=i,s='';for(var k=0;k<L;k++){s=CHARS[x%CHARS.length]+s;x=Math.floor(x/CHARS.length);}out.push(s);}return out;}"
            + "function cRect(e){var r=e.getBoundingClientRect();return r.top>=-4&&r.left>=-4&&r.bottom<=window.innerHeight+4&&r.left<=window.innerWidth-4&&r.width>1&&r.height>1;}"
            + "function showHints(){"
            + "  hideHints();"
            + "  var links=[];var all=document.querySelectorAll('a[href],button,input[type=submit],[onclick],area[href]');"
            + "  for(var i=0;i<all.length;i++){if(cRect(all[i])&&links.length<400)links.push(all[i]);}"
            + "  if(!links.length)return;"
            + "  var L=labels(links.length);"
            + "  hintHolder=document.createElement('div');"
            + "  hintHolder.style.cssText='position:fixed;left:0;top:0;z-index:2147483647;pointer-events:none;';"
            + "  document.body.appendChild(hintHolder);"
            + "  for(var j=0;j<links.length;j++){var r=links[j].getBoundingClientRect();var d=document.createElement('span');"
            + "    d.style.cssText='position:fixed;left:'+(r.left+2)+'px;top:'+(r.top+2)+'px;background:#1a73e8;color:#fff;font:bold 11px/14px monospace;padding:1px 4px;border-radius:3px;box-shadow:0 1px 2px rgba(0,0,0,.4);';"
            + "    d.textContent=L[j];hintHolder.appendChild(d);hintNodes.push(links[j]);hintLabels.push(L[j]);}"
            + "  MODE='hint';hintSel='';"
            + "}"
            + "function hideHints(){if(hintHolder&&hintHolder.parentNode)hintHolder.parentNode.removeChild(hintHolder);hintHolder=null;hintNodes=[];hintLabels=[];hintSel='';if(MODE==='hint')MODE='normal';}"
            + "function tryHint(ch){hintSel+=ch;var hit=-1,partial=false;"
            + "  for(var i=0;i<hintLabels.length;i++){if(hintLabels[i]===hintSel){hit=i;}else if(hintLabels[i].indexOf(hintSel)===0)partial=true;}"
            + "  if(hit>=0){var el=hintNodes[hit];hideHints();fire(el);return true;}"
            + "  if(!partial){hideHints();return true;}"
            + "  return false;"
            + "}"
            + "function fire(el){try{el.click();}catch(e){try{el.dispatchEvent(new MouseEvent('click',{bubbles:true}));}catch(e2){}}}"
            + "function sc(x,y){window.scrollBy({left:x,top:y,behavior:'auto'});}"
            + "function findInPage(){var q=prompt('Find:');if(q){if(window.find){window.find(q,false,false,true,false,true,true);}else if(!document.execCommand('HiliteColor',false,'transparent')){}}}"
            + "function nav(a){try{__mbNav.action(a);}catch(e){}}"
            + "function press(k){"
            + "  if(MODE==='hint'){if(k==='Escape'){hideHints();}else if(k.length===1){tryHint(k.toLowerCase());}return true;}"
            + "  if(typing())return false;"
            + "  if(k==='Escape'){clr();return true;}"
            + "  buf=(buf+k).slice(-2);"
            + "  var one={s:'d',w:'u',j:'jd',k:'ku',h:'hl',l:'hr',r:'reload',x:'stop',f:'hints',H:'back',L:'fwd',gg:'top',G:'bottom',J:'halfd',K:'halfu',yy:'copyurl','/':'find',n:'next',N:'prev'};"
            + "  if(buf==='f'){showHints();clr();return true;}"
            + "  if(one[buf]){run(one[buf]);clr();return true;}"
            + "  if(one[k]){run(one[k]);clr();return true;}"
            + "  var hasStart=false;for(var key in one){if(one.hasOwnProperty(key)&&key.indexOf(buf)===0){hasStart=true;break;}}"
            + "  if(!hasStart)clr();"
            + "  return true;"
            + "}"
            + "function run(a){"
            + "  switch(a){"
            + "    case 'd':sc(0,180);break;"
            + "    case 'u':sc(0,-180);break;"
            + "    case 'jd':sc(0,120);break;"
            + "    case 'ku':sc(0,-120);break;"
            + "    case 'halfd':sc(0,window.innerHeight/2);break;"
            + "    case 'halfu':sc(0,-window.innerHeight/2);break;"
            + "    case 'hl':sc(-120,0);break;"
            + "    case 'hr':sc(120,0);break;"
            + "    case 'top':window.scrollTo(0,0);break;"
            + "    case 'bottom':window.scrollTo(0,document.body.scrollHeight);break;"
            + "    case 'reload':nav('reload');break;"
            + "    case 'stop':nav('stop');break;"
            + "    case 'back':nav('back');break;"
            + "    case 'fwd':nav('fwd');break;"
            + "    case 'copyurl':try{var t=document.title||'';__mbNav.copy(location.href);}catch(e){}break;"
            + "    case 'find':findInPage();break;"
            + "    case 'next':break;"
            + "    case 'prev':break;"
            + "  }"
            + "}"
            + "document.addEventListener('keydown',function(e){"
            + "  var k=e.key;"
            + "  if(k==='Shift'){return;}"
            + "  if(k.length===1&&k.match(/[a-zA-Z/]/)){var cap=k.toUpperCase()===k&&k.toLowerCase()!==k;"
            + "    var ch=cap?k:k.toLowerCase();if(press(cap?k:ch)){e.preventDefault();e.stopPropagation();}}"
            + "  else if(k==='Escape'){if(MODE==='hint'){hideHints();}else{clr();}e.preventDefault();}"
            + "},true);"
            + "window.addEventListener('blur',function(){if(MODE==='hint')hideHints();clr();});"
            + "})();";
    }
}
